version: "1"

services:
  flaskblog:
    image: dogukanurker/flaskblog:latest
    container_name: flaskblog
    restart: always
    build: .
    volumes:
      - .:/app
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/nginx/ssl/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certbot/:/var/www/certbot
    ports:
      - 80:80
      - 443:443
